blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ SocioSell Community Discussions
    url: https://github.com/Varsha-1605/SocioSell/discussions
    about: Please ask and answer questions in our community discussions
    
  - name: ğŸ“š SocioSell Documentation
    url: https://github.com/Varsha-1605/SocioSell#readme
    about: Check our documentation for answers
    
  - name: ğŸ“§ Contact Support
    url: mailto:varshadewangan1605@gmail.com
    about: Contact the maintainer directly
    
  - name: ğŸŒ Join the SocioSell Discord Community
    url: https://discord.gg/n34tSJ3TBs
    about: Connect with our community on Discord for live discussions and support
